{% set version = '1.17.1.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-catools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/caTools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/caTools/caTools_{{ version }}.tar.gz
  sha256: d53e2c5c77f1bd4744703d7196dbc9b4671a120bbb5b9b3edc45fc57c0650c06

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: MASS, rpart
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-bitops

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-bitops

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('caTools')"           # [not win]
    - "\"%R%\" -e \"library('caTools')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=caTools
  license: GPL-3
  summary: 'Contains several basic utility functions including: moving (rolling, running) window
    statistic functions, read/write for GIF and ENVI binary files, fast calculation
    of AUC, LogitBoost classifier, base64 encoder/decoder, round-off-error-free sum
    and cumsum, etc.'

  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: caTools
# Type: Package
# Title: Tools: moving window statistics, GIF, Base64, ROC AUC, etc.
# Version: 1.17.1.1
# Date: 2014-04-21
# Author: Jarek Tuszynski <jaroslaw.w.tuszynski@saic.com>
# Maintainer: ORPHANED
# Depends: R (>= 2.2.0)
# Imports: bitops
# Suggests: MASS, rpart
# Description: Contains several basic utility functions including: moving (rolling, running) window statistic functions, read/write for GIF and ENVI binary files, fast calculation of AUC, LogitBoost classifier, base64 encoder/decoder, round-off-error-free sum and cumsum, etc.
# License: GPL-3
# Packaged: 2018-07-20 09:19:33 UTC; hornik
# NeedsCompilation: yes
# Repository: CRAN
# Date/Publication: 2018-07-20 12:43:28 UTC
# X-CRAN-Original-Maintainer: Harutyun Khachatryan <kh_harut@yahoo.com>
# X-CRAN-Comment: Orphaned and corrected on 2018-07-20 as check problems were not corrected despite reminders.

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
