travis:
  secure:
    BINSTAR_TOKEN: bdMs4ZZTZZJaRAAaCR2mCXOVcpsyI/nsDMkDgSBDNxt64E6Dh+kP6unvlfIms+se/5+VzKdoYkTqMZbsLTI4S83XYNnBAUEjWz+G5E5jNBa6wEXNVOlJxvuvCkfbr3qExTtxgUJNZuaBmsz0JTTKgcYLPqxZe+B/cpTZn7nm2Jjvxo7Jxrys6QfI/8DJ0SyxHvcdgRRHLF66jJOY0oFoaDbR2IkmmBK3xI+FqAhZT9l0rVbrlj5h1m5wSwntJXsGbycTE5T/xUTe610MgsB8fSKjz9cir8n2tPzWUllpYWeVYA1zRi4cKtwKjAXoy9z1uDlH4vXtgL2F81ISldkoxSj0fMaA1tQkSSbtwhUGoKFPCt6hyfvTR2/DDbvqLeTKyHyt7UhBmpNwzXnoE1Tyk4ydN8/EHc5TbeJ79haD7VzgeXLUjqgOG9JdS+WIzilgLtIzloHxaydAJ69rrIPgBQfxSj+47PF3e7uHlF0/rdjABidEVZGwFdVL2YmirFJ/AwIXT5U4c3xoSVq2GPy43IsBXrZEcLz8+4Js+NXC6fwHNz7LHQaF8LgG5IC7fVbcmVG04x39WHMXAGi8f+j6Xkiz6gkGuxoYi6X957xo3F3ehUgAlnkA8tiX3oqaTbUE3Wy0H39pZeEVYnyZ9uIGoFG/Flnkj5WgnO5/TtqMGio=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
