travis:
  secure:
    BINSTAR_TOKEN: rfIZ0rlx/QPrcC427rHyoCKBOSV9MzEow31DScJwewIAGR7q4OPSTPqVVfV8pOMZ6i6MjLixpZqqnYkZ9sRrsPLylYnXNh5+G78pqMNwckl8Kom/mcbitvXClWWKh4FBCBHKUU4S8PXt5Cf/kWKn81iEC7fblPYVayAKIB23qt8lQ8ABtX2skl6h8bEjB1YMccy+9Sx2QNq19WcNSB2OIrwoEiwbJZucv6prHTSZeytp/lX5/okLJMZGgHRX3U6S5Gg44ybrSi89y2tK1WSwGHbYc+3qaI/R1oMSsDG/smVDsU9ruzApTylUHLeu0i1UBC2/jLKsmyj/wa7p021xevN6Dt25/dPJK8iRTqcUggwZUWWMWNCotVg8HmPTdRYHiTzQMQavVlzQmAKJ44RzIyKaZ0ww36bcsppX93eWtQq1aObpwQHQIfzpWRQ68IgZWJdoH2L/4Yz42uapO1x2Db0fYCyB2LalRTh21YNSjZAlExYZvNENNqWZguTAYRXAHzoON4Gu4qOWCMq/DCaoDz+QTE1XevOaAkrVXzUr3DTj0vQQFcqSdcnG3RWqqW+3a4KvoTV4QKpH3nSeka2RzEJbxPhQrFBnnx7HOfUMz6VxjipCECXLekphc89Eu4um8GROtbaaoj5P9+g+Z4F81ZRV1o99pSrIssMvk4ZdeCQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
