travis:
  secure:
    BINSTAR_TOKEN: z7adRDJVdI8hBARzyOf7g4uiyVH4rF0yADnbFL++bsj6vrfmNFmTqQe5Edz4uBtgZNzdsbS7OFnOmgouqEjbLfJ8cLRevhlwUd+OBsUjOhHEV4wDaIOPkTuZYScj/byp6QZJLParaSu5LXmFDnHi17fsv70fxFhvBaBOBV3BKzCGFrJVKHYrnN5og4wXnxL7E2j5/iHtwIekh42br8PS23DkVCpay/wAneAZbIN8Z2RvSYVbxAclH998GuxpzXkfgoEtOisog6FBSTJFe53vEMJbskoFAUsXG+xRP4T3HxNlEpCnddzpswjwFOY3Tk2SfqJ1pcV8RvmbvnIqgxiZRQhcpty2+lm/2wfMnGu7xhv62rRo8gGx40Oy0GxfHnZ1QkuS15hiVcdzZm9Q9IDh4hkKt0TbXy+583MycJXiVKIrZLutZaqqs7IhtZ/aCABelLRyrTZZeuDzp96lMY/crSxJEioxVgNcWxj2r0sDsRJMh1wD7OVXG6lEy39Y+hiWnPRB0ScB5N0V1qceY/LM2Jf7dbhp/jOR7ULXsw2P/yiB4xj/8zHki27fd/qxR1sMsdGT2EXoXxDzc4MEyUCmKWhcibEk5VbTFkAmkoEGiJ6DbAhYtayxpd2Gq3jbdbolXBCX2OXtm8iRXrtCtp5DM5T4eERyasz659z8tQjH3eY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
